# ======================================
# 雲流システム - Spring Boot基本設定
# Copyright (c) 2024 株式会社アプサ
# ======================================

spring:
  application:
    name: unryu
  
  # プロファイル設定
  profiles:
    active: dev
  
  # データソース基本設定
  datasource:
    url: jdbc:postgresql://localhost:5432/unryu_db
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    
  # JPA/Hibernate基本設定
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    
  # Flyway マイグレーション設定
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    encoding: UTF-8
    
  # Thymeleaf基本設定
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    
  # Web設定
  web:
    locale: ja_JP
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    
  # セキュリティ設定
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - email
              - profile
              
  # ファイルアップロード設定
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      
  # キャッシュ設定
  cache:
    type: simple
    
  # メール設定
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# サーバー基本設定
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  error:
    include-stacktrace: never
    include-message: always

# ログ基本設定
logging:
  config: classpath:logback-spring.xml
  level:
    jp.co.apsa.unryu: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 監査ログ設定
audit:
  logging:
    enabled: true
    level: INFO
  database:
    enabled: true
  security:
    enabled: true
  async:
    enabled: true
  retention:
    days: 365

# 雲流システム独自設定
unryu:
  # ファイル保存設定
  file:
    upload-dir: ${UPLOAD_DIR:./uploads}
    max-size: 10MB
    allowed-extensions: 
      - pdf
      - jpg
      - jpeg
      - png
      - doc
      - docx
      - xls
      - xlsx
      
  # Slack通知設定
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL:}
    enabled: ${SLACK_ENABLED:false}
    
  # 承認設定
  approval:
    max-steps: 5
    timeout-days: 30
    
  # JWT設定
  jwt:
    secret: ${JWT_SECRET:unryu-secret-key-change-in-production}
    expiration: 86400 # 24時間

# Management/Actuator設定
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
