# ======================================
# 技育システム - 開発環境設定
# Copyright (c) 2024 株式会社アプサ
# ======================================

spring:
  # 開発環境データソース
  datasource:
    url: jdbc:postgresql://db:5432/giiku_db_autotest
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
    
  # JPA設定（開発環境）
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        
  # Flyway（開発環境）
  flyway:
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true
    
  # Thymeleaf（開発環境）
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    
  # DevTools設定
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
      port: 35729
    
  # 開発用H2コンソール設定（使用しない場合は無効のまま）
  h2:
    console:
      enabled: false
      
  # セキュリティ（開発環境）
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dev-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dev-client-secret}

# サーバー設定（開発環境）
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always

# ログ設定（開発環境）
logging:
  level:
    jp.co.apsa.giiku: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 技育システム設定（開発環境）
giiku:
  # ファイル設定
  file:
    upload-dir: ./uploads/dev
    
  # Slack通知（開発環境は無効）
  slack:
    enabled: false
    webhook-url: ""
    
  # JWT設定（開発環境）
  jwt:
    secret: dev-secret-key-do-not-use-in-production
    expiration: 86400 # 24時間
    
  # 承認設定（開発環境）
  approval:
    max-steps: 3
    timeout-days: 7

# Management設定（開発環境）
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
